// 아프리카 국가 데이터
export const africaCountries = [
    { name: "나이지리아", continent: "africa", flag: "🇳🇬", capital: "아부자", population: "2.1억명", area: "923,768 km²" },
    { name: "이집트", continent: "africa", flag: "🇪🇬", capital: "카이로", population: "1.0억명", area: "1,001,450 km²" },
    { name: "에티오피아", continent: "africa", flag: "🇪🇹", capital: "아디스아바바", population: "1.1억명", area: "1,104,300 km²" },
    { name: "콩고민주공화국", continent: "africa", flag: "🇨🇩", capital: "킨샤사", population: "9,000만명", area: "2,344,858 km²" },
    { name: "탄자니아", continent: "africa", flag: "🇹🇿", capital: "도도마", population: "6,000만명", area: "947,303 km²" },
    { name: "남아프리카공화국", continent: "africa", flag: "🇿🇦", capital: "프리토리아", population: "5,900만명", area: "1,221,037 km²" },
    { name: "케냐", continent: "africa", flag: "🇰🇪", capital: "나이로비", population: "5,400만명", area: "580,367 km²" },
    { name: "우간다", continent: "africa", flag: "🇺🇬", capital: "캄팔라", population: "4,500만명", area: "241,550 km²" },
    { name: "알제리", continent: "africa", flag: "🇩🇿", capital: "알제", population: "4,400만명", area: "2,381,741 km²" },
    { name: "수단", continent: "africa", flag: "🇸🇩", capital: "하르툼", population: "4,400만명", area: "1,886,068 km²" },
    { name: "모로코", continent: "africa", flag: "🇲🇦", capital: "라바트", population: "3,700만명", area: "446,550 km²" },
    { name: "앙골라", continent: "africa", flag: "🇦🇴", capital: "루안다", population: "3,300만명", area: "1,246,700 km²" },
    { name: "가나", continent: "africa", flag: "🇬🇭", capital: "아크라", population: "3,100만명", area: "238,535 km²" },
    { name: "모잠비크", continent: "africa", flag: "🇲🇿", capital: "마푸토", population: "3,100만명", area: "801,590 km²" },
    { name: "마다가스카르", continent: "africa", flag: "🇲🇬", capital: "안타나나리보", population: "2,800만명", area: "587,041 km²" },
    { name: "카메룬", continent: "africa", flag: "🇨🇲", capital: "야운데", population: "2,700만명", area: "475,442 km²" },
    { name: "코트디부아르", continent: "africa", flag: "🇨🇮", capital: "야무수크로", population: "2,600만명", area: "322,463 km²" },
    { name: "니제르", continent: "africa", flag: "🇳🇪", capital: "니아메", population: "2,500만명", area: "1,267,000 km²" },
    { name: "부르키나파소", continent: "africa", flag: "🇧🇫", capital: "와가두구", population: "2,100만명", area: "274,200 km²" },
    { name: "말리", continent: "africa", flag: "🇲🇱", capital: "바마코", population: "2,000만명", area: "1,240,192 km²" },
    { name: "말라위", continent: "africa", flag: "🇲🇼", capital: "릴롱궤", population: "1,900만명", area: "118,484 km²" },
    { name: "잠비아", continent: "africa", flag: "🇿🇲", capital: "루사카", population: "1,800만명", area: "752,618 km²" },
    { name: "세네갈", continent: "africa", flag: "🇸🇳", capital: "다카르", population: "1,700만명", area: "196,722 km²" },
    { name: "차드", continent: "africa", flag: "🇹🇩", capital: "은자메나", population: "1,600만명", area: "1,284,000 km²" },
    { name: "소말리아", continent: "africa", flag: "🇸🇴", capital: "모가디슈", population: "1,600만명", area: "637,657 km²" },
    { name: "짐바브웨", continent: "africa", flag: "🇿🇼", capital: "하라레", population: "1,500만명", area: "390,757 km²" },
    { name: "기니", continent: "africa", flag: "🇬🇳", capital: "코나크리", population: "1,300만명", area: "245,857 km²" },
    { name: "르완다", continent: "africa", flag: "🇷🇼", capital: "키갈리", population: "1,300만명", area: "26,338 km²" },
    { name: "베냉", continent: "africa", flag: "🇧🇯", capital: "포르토노보", population: "1,200만명", area: "114,763 km²" },
    { name: "부룬디", continent: "africa", flag: "🇧🇮", capital: "기테가", population: "1,200만명", area: "27,830 km²" },
    { name: "튀니지", continent: "africa", flag: "🇹🇳", capital: "튀니스", population: "1,200만명", area: "163,610 km²" },
    { name: "남수단", continent: "africa", flag: "🇸🇸", capital: "주바", population: "1,100만명", area: "619,745 km²" },
    { name: "토고", continent: "africa", flag: "🇹🇬", capital: "로메", population: "800만명", area: "56,785 km²" },
    { name: "시에라리온", continent: "africa", flag: "🇸🇱", capital: "프리타운", population: "800만명", area: "71,740 km²" },
    { name: "리비아", continent: "africa", flag: "🇱🇾", capital: "트리폴리", population: "700만명", area: "1,759,540 km²" },
    { name: "콩고공화국", continent: "africa", flag: "🇨🇬", capital: "브라자빌", population: "500만명", area: "342,000 km²" },
    { name: "중앙아프리카공화국", continent: "africa", flag: "🇨🇫", capital: "방기", population: "500만명", area: "622,984 km²" },
    { name: "라이베리아", continent: "africa", flag: "🇱🇷", capital: "몬로비아", population: "500만명", area: "111,369 km²" },
    { name: "모리타니", continent: "africa", flag: "🇲🇷", capital: "누악쇼트", population: "400만명", area: "1,030,700 km²" },
    { name: "에리트레아", continent: "africa", flag: "🇪🇷", capital: "아스마라", population: "400만명", area: "117,600 km²" },
    { name: "나미비아", continent: "africa", flag: "🇳🇦", capital: "빈트후크", population: "300만명", area: "825,615 km²" },
    { name: "감비아", continent: "africa", flag: "🇬🇲", capital: "반줄", population: "200만명", area: "11,295 km²" },
    { name: "보츠와나", continent: "africa", flag: "🇧🇼", capital: "가보로네", population: "200만명", area: "581,730 km²" },
    { name: "가봉", continent: "africa", flag: "🇬🇦", capital: "리브르빌", population: "200만명", area: "267,667 km²" },
    { name: "레소토", continent: "africa", flag: "🇱🇸", capital: "마세루", population: "200만명", area: "30,355 km²" },
    { name: "기니비사우", continent: "africa", flag: "🇬🇼", capital: "비사우", population: "200만명", area: "36,125 km²" },
    { name: "적도기니", continent: "africa", flag: "🇬🇶", capital: "말라보", population: "100만명", area: "28,051 km²" },
    { name: "모리셔스", continent: "africa", flag: "🇲🇺", capital: "포트루이스", population: "100만명", area: "2,040 km²" },
    { name: "에스와티니", continent: "africa", flag: "🇸🇿", capital: "음바바네", population: "100만명", area: "17,364 km²" },
    { name: "지부티", continent: "africa", flag: "🇩🇯", capital: "지부티", population: "100만명", area: "23,200 km²" },
    { name: "코모로", continent: "africa", flag: "🇰🇲", capital: "모로니", population: "90만명", area: "1,862 km²" },
    { name: "카보베르데", continent: "africa", flag: "🇨🇻", capital: "프라이아", population: "60만명", area: "4,033 km²" },
    { name: "상투메프린시페", continent: "africa", flag: "🇸🇹", capital: "상투메", population: "20만명", area: "964 km²" },
    { name: "세이셸", continent: "africa", flag: "🇸🇨", capital: "빅토리아", population: "10만명", area: "455 km²" }
]; 