// 아시아권 국가 데이터
export const asiaCountries = [
    { name: "대한민국", continent: "asia", flag: "🇰🇷", capital: "서울", population: "5,200만명", area: "100,363 km²" },
    { name: "일본", continent: "asia", flag: "🇯🇵", capital: "도쿄", population: "1.25억명", area: "377,975 km²" },
    { name: "중국", continent: "asia", flag: "🇨🇳", capital: "베이징", population: "14억명", area: "9,596,961 km²" },
    { name: "북한", continent: "asia", flag: "🇰🇵", capital: "평양", population: "2,500만명", area: "120,540 km²" },
    { name: "몽골", continent: "asia", flag: "🇲🇳", capital: "울란바토르", population: "330만명", area: "1,564,110 km²" },
    { name: "타이완", continent: "asia", flag: "🇹🇼", capital: "타이페이", population: "2,350만명", area: "36,193 km²" },
    { name: "홍콩", continent: "asia", flag: "🇭🇰", capital: "홍콩", population: "750만명", area: "1,104 km²" },
    { name: "마카오", continent: "asia", flag: "🇲🇴", capital: "마카오", population: "68만명", area: "32.9 km²" },
    { name: "베트남", continent: "asia", flag: "🇻🇳", capital: "하노이", population: "9,700만명", area: "331,212 km²" },
    { name: "태국", continent: "asia", flag: "🇹🇭", capital: "방콕", population: "6,900만명", area: "513,120 km²" },
    { name: "캄보디아", continent: "asia", flag: "🇰🇭", capital: "프놈펜", population: "1,670만명", area: "181,035 km²" },
    { name: "라오스", continent: "asia", flag: "🇱🇦", capital: "비엔티안", population: "730만명", area: "236,800 km²" },
    { name: "미얀마", continent: "asia", flag: "🇲🇲", capital: "네피도", population: "5,400만명", area: "676,578 km²" },
    { name: "말레이시아", continent: "asia", flag: "🇲🇾", capital: "쿠알라룸푸르", population: "3,200만명", area: "330,803 km²" },
    { name: "싱가포르", continent: "asia", flag: "🇸🇬", capital: "싱가포르", population: "570만명", area: "728.6 km²" },
    { name: "인도네시아", continent: "asia", flag: "🇮🇩", capital: "자카르타", population: "2.7억명", area: "1,904,569 km²" },
    { name: "필리핀", continent: "asia", flag: "🇵🇭", capital: "마닐라", population: "1.1억명", area: "300,000 km²" },
    { name: "브루나이", continent: "asia", flag: "🇧🇳", capital: "반다르스리브가완", population: "44만명", area: "5,765 km²" },
    { name: "동티모르", continent: "asia", flag: "🇹🇱", capital: "딜리", population: "130만명", area: "14,874 km²" },
    { name: "인도", continent: "asia", flag: "🇮🇳", capital: "뉴델리", population: "14억명", area: "3,287,263 km²" },
    { name: "파키스탄", continent: "asia", flag: "🇵🇰", capital: "이슬라마바드", population: "2.2억명", area: "796,095 km²" },
    { name: "방글라데시", continent: "asia", flag: "🇧🇩", capital: "다카", population: "1.7억명", area: "147,570 km²" },
    { name: "스리랑카", continent: "asia", flag: "🇱🇰", capital: "콜롬보", population: "2,200만명", area: "65,610 km²" },
    { name: "네팔", continent: "asia", flag: "🇳🇵", capital: "카트만두", population: "2,900만명", area: "147,181 km²" },
    { name: "부탄", continent: "asia", flag: "🇧🇹", capital: "팀푸", population: "77만명", area: "38,394 km²" },
    { name: "몰디브", continent: "asia", flag: "🇲🇻", capital: "말레", population: "54만명", area: "298 km²" },
    { name: "아프가니스탄", continent: "asia", flag: "🇦🇫", capital: "카불", population: "3,800만명", area: "652,230 km²" },
    { name: "카자흐스탄", continent: "asia", flag: "🇰🇿", capital: "누르술탄", population: "1,900만명", area: "2,724,900 km²" },
    { name: "우즈베키스탄", continent: "asia", flag: "🇺🇿", capital: "타슈켄트", population: "3,400만명", area: "447,400 km²" },
    { name: "키르기스스탄", continent: "asia", flag: "🇰🇬", capital: "비슈케크", population: "650만명", area: "199,951 km²" },
    { name: "타지키스탄", continent: "asia", flag: "🇹🇯", capital: "두샨베", population: "950만명", area: "143,100 km²" },
    { name: "투르크메니스탄", continent: "asia", flag: "🇹🇲", capital: "아시가바트", population: "600만명", area: "488,100 km²" },
    { name: "아제르바이잔", continent: "asia", flag: "🇦🇿", capital: "바쿠", population: "1,000만명", area: "86,600 km²" },
    { name: "조지아", continent: "asia", flag: "🇬🇪", capital: "트빌리시", population: "370만명", area: "69,700 km²" },
    { name: "아르메니아", continent: "asia", flag: "🇦🇲", capital: "예레반", population: "300만명", area: "29,743 km²" },
    { name: "이란", continent: "asia", flag: "🇮🇷", capital: "테헤란", population: "8,400만명", area: "1,648,195 km²" },
    { name: "이라크", continent: "asia", flag: "🇮🇶", capital: "바그다드", population: "4,000만명", area: "438,317 km²" },
    { name: "쿠웨이트", continent: "asia", flag: "🇰🇼", capital: "쿠웨이트시티", population: "430만명", area: "17,818 km²" },
    { name: "사우디아라비아", continent: "asia", flag: "🇸🇦", capital: "리야드", population: "3,500만명", area: "2,149,690 km²" },
    { name: "바레인", continent: "asia", flag: "🇧🇭", capital: "마나마", population: "170만명", area: "765 km²" },
    { name: "카타르", continent: "asia", flag: "🇶🇦", capital: "도하", population: "290만명", area: "11,586 km²" },
    { name: "아랍에미리트", continent: "asia", flag: "🇦🇪", capital: "아부다비", population: "990만명", area: "83,600 km²" },
    { name: "오만", continent: "asia", flag: "🇴🇲", capital: "무스카트", population: "510만명", area: "309,500 km²" },
    { name: "예멘", continent: "asia", flag: "🇾🇪", capital: "사나", population: "3,000만명", area: "527,968 km²" },
    { name: "요르단", continent: "asia", flag: "🇯🇴", capital: "암만", population: "1,000만명", area: "89,342 km²" },
    { name: "레바논", continent: "asia", flag: "🇱🇧", capital: "베이루트", population: "680만명", area: "10,452 km²" },
    { name: "시리아", continent: "asia", flag: "🇸🇾", capital: "다마스쿠스", population: "1,800만명", area: "185,180 km²" },
    { name: "이스라엘", continent: "asia", flag: "🇮🇱", capital: "예루살렘", population: "930만명", area: "20,770 km²" },
    { name: "팔레스타인", continent: "asia", flag: "🇵🇸", capital: "라말라", population: "500만명", area: "6,220 km²" },
    { name: "키프로스", continent: "asia", flag: "🇨🇾", capital: "니코시아", population: "120만명", area: "9,251 km²" },
    { name: "터키", continent: "asia", flag: "🇹🇷", capital: "앙카라", population: "8,400만명", area: "783,562 km²" }
]; 