// 유럽 국가 데이터
export const europeCountries = [
    { name: "프랑스", continent: "europe", flag: "🇫🇷", capital: "파리", population: "6,700만명", area: "551,695 km²" },
    { name: "독일", continent: "europe", flag: "🇩🇪", capital: "베를린", population: "8,300만명", area: "357,022 km²" },
    { name: "영국", continent: "europe", flag: "🇬🇧", capital: "런던", population: "6,700만명", area: "242,495 km²" },
    { name: "이탈리아", continent: "europe", flag: "🇮🇹", capital: "로마", population: "6,000만명", area: "301,340 km²" },
    { name: "스페인", continent: "europe", flag: "🇪🇸", capital: "마드리드", population: "4,700만명", area: "505,990 km²" },
    { name: "폴란드", continent: "europe", flag: "🇵🇱", capital: "바르샤바", population: "3,800만명", area: "312,696 km²" },
    { name: "루마니아", continent: "europe", flag: "🇷🇴", capital: "부쿠레슈티", population: "1,900만명", area: "238,397 km²" },
    { name: "네덜란드", continent: "europe", flag: "🇳🇱", capital: "암스테르담", population: "1,700만명", area: "41,543 km²" },
    { name: "벨기에", continent: "europe", flag: "🇧🇪", capital: "브뤼셀", population: "1,200만명", area: "30,528 km²" },
    { name: "체코", continent: "europe", flag: "🇨🇿", capital: "프라하", population: "1,100만명", area: "78,867 km²" },
    { name: "그리스", continent: "europe", flag: "🇬🇷", capital: "아테네", population: "1,100만명", area: "131,957 km²" },
    { name: "포르투갈", continent: "europe", flag: "🇵🇹", capital: "리스본", population: "1,000만명", area: "92,090 km²" },
    { name: "스웨덴", continent: "europe", flag: "🇸🇪", capital: "스톡홀름", population: "1,000만명", area: "450,295 km²" },
    { name: "헝가리", continent: "europe", flag: "🇭🇺", capital: "부다페스트", population: "970만명", area: "93,028 km²" },
    { name: "오스트리아", continent: "europe", flag: "🇦🇹", capital: "비엔나", population: "900만명", area: "83,871 km²" },
    { name: "스위스", continent: "europe", flag: "🇨🇭", capital: "베른", population: "870만명", area: "41,277 km²" },
    { name: "불가리아", continent: "europe", flag: "🇧🇬", capital: "소피아", population: "690만명", area: "110,879 km²" },
    { name: "덴마크", continent: "europe", flag: "🇩🇰", capital: "코펜하겐", population: "580만명", area: "43,094 km²" },
    { name: "핀란드", continent: "europe", flag: "🇫🇮", capital: "헬싱키", population: "550만명", area: "338,424 km²" },
    { name: "슬로바키아", continent: "europe", flag: "🇸🇰", capital: "브라티슬라바", population: "550만명", area: "49,035 km²" },
    { name: "노르웨이", continent: "europe", flag: "🇳🇴", capital: "오슬로", population: "540만명", area: "385,207 km²" },
    { name: "아일랜드", continent: "europe", flag: "🇮🇪", capital: "더블린", population: "490만명", area: "70,273 km²" },
    { name: "크로아티아", continent: "europe", flag: "🇭🇷", capital: "자그레브", population: "410만명", area: "56,594 km²" },
    { name: "세르비아", continent: "europe", flag: "🇷🇸", capital: "베오그라드", population: "870만명", area: "88,361 km²" },
    { name: "슬로베니아", continent: "europe", flag: "🇸🇮", capital: "류블랴나", population: "210만명", area: "20,273 km²" },
    { name: "리투아니아", continent: "europe", flag: "🇱🇹", capital: "빌뉴스", population: "280만명", area: "65,300 km²" },
    { name: "라트비아", continent: "europe", flag: "🇱🇻", capital: "리가", population: "190만명", area: "64,589 km²" },
    { name: "에스토니아", continent: "europe", flag: "🇪🇪", capital: "탈린", population: "130만명", area: "45,227 km²" },
    { name: "몰도바", continent: "europe", flag: "🇲🇩", capital: "키시너우", population: "260만명", area: "33,846 km²" },
    { name: "알바니아", continent: "europe", flag: "🇦🇱", capital: "티라나", population: "290만명", area: "28,748 km²" },
    { name: "북마케도니아", continent: "europe", flag: "🇲🇰", capital: "스코페", population: "210만명", area: "25,713 km²" },
    { name: "보스니아 헤르체고비나", continent: "europe", flag: "🇧🇦", capital: "사라예보", population: "330만명", area: "51,197 km²" },
    { name: "몬테네그로", continent: "europe", flag: "🇲🇪", capital: "포드고리차", population: "62만명", area: "13,812 km²" },
    { name: "코소보", continent: "europe", flag: "🇽🇰", capital: "프리슈티나", population: "180만명", area: "10,908 km²" },
    { name: "아이슬란드", continent: "europe", flag: "🇮🇸", capital: "레이캬비크", population: "36만명", area: "103,000 km²" },
    { name: "룩셈부르크", continent: "europe", flag: "🇱🇺", capital: "룩셈부르크시티", population: "63만명", area: "2,586 km²" },
    { name: "몰타", continent: "europe", flag: "🇲🇹", capital: "발레타", population: "51만명", area: "316 km²" },
    { name: "리히텐슈타인", continent: "europe", flag: "🇱🇮", capital: "파두츠", population: "38,000명", area: "160 km²" },
    { name: "모나코", continent: "europe", flag: "🇲🇨", capital: "모나코", population: "39,000명", area: "2.02 km²" },
    { name: "산마리노", continent: "europe", flag: "🇸🇲", capital: "산마리노", population: "34,000명", area: "61 km²" },
    { name: "바티칸", continent: "europe", flag: "🇻🇦", capital: "바티칸시티", population: "825명", area: "0.44 km²" },
    { name: "안도라", continent: "europe", flag: "🇦🇩", capital: "안도라라벨랴", population: "77,000명", area: "468 km²" },
    { name: "우크라이나", continent: "europe", flag: "🇺🇦", capital: "키예프", population: "4,400만명", area: "603,550 km²" },
    { name: "벨라루스", continent: "europe", flag: "🇧🇾", capital: "민스크", population: "940만명", area: "207,600 km²" },
    { name: "러시아", continent: "europe", flag: "🇷🇺", capital: "모스크바", population: "1.4억명", area: "17,098,246 km²" }
]; 