// 오세아니아 국가 데이터
export const oceaniaCountries = [
    { name: "호주", continent: "oceania", flag: "🇦🇺", capital: "캔버라", population: "2,500만명", area: "7,692,024 km²" },
    { name: "뉴질랜드", continent: "oceania", flag: "🇳🇿", capital: "웰링턴", population: "510만명", area: "268,021 km²" },
    { name: "파푸아뉴기니", continent: "oceania", flag: "🇵🇬", capital: "포트모르즈비", population: "900만명", area: "462,840 km²" },
    { name: "피지", continent: "oceania", flag: "🇫🇯", capital: "수바", population: "90만명", area: "18,274 km²" },
    { name: "솔로몬 제도", continent: "oceania", flag: "🇸🇧", capital: "호니아라", population: "70만명", area: "28,896 km²" },
    { name: "바누아투", continent: "oceania", flag: "🇻🇺", capital: "포트빌라", population: "30만명", area: "12,189 km²" },
    { name: "뉴칼레도니아", continent: "oceania", flag: "🇳🇨", capital: "누메아", population: "28만명", area: "18,575 km²" },
    { name: "프랑스령 폴리네시아", continent: "oceania", flag: "🇵🇫", capital: "파페에테", population: "28만명", area: "4,167 km²" },
    { name: "사모아", continent: "oceania", flag: "🇼🇸", capital: "아피아", population: "20만명", area: "2,842 km²" },
    { name: "키리바시", continent: "oceania", flag: "🇰🇮", capital: "타라와", population: "12만명", area: "811 km²" },
    { name: "미크로네시아", continent: "oceania", flag: "🇫🇲", capital: "팔리키르", population: "11만명", area: "702 km²" },
    { name: "통가", continent: "oceania", flag: "🇹🇴", capital: "누쿠알로파", population: "11만명", area: "747 km²" },
    { name: "마셜 제도", continent: "oceania", flag: "🇲🇭", capital: "마주로", population: "6만명", area: "181 km²" },
    { name: "팔라우", continent: "oceania", flag: "🇵🇼", capital: "멜레케오크", population: "2만명", area: "459 km²" },
    { name: "투발루", continent: "oceania", flag: "🇹🇻", capital: "푸나푸티", population: "12,000명", area: "26 km²" },
    { name: "나우루", continent: "oceania", flag: "🇳🇷", capital: "야렌", population: "11,000명", area: "21 km²" },
    { name: "쿡 제도", continent: "oceania", flag: "🇨🇰", capital: "아바루아", population: "17,000명", area: "236 km²" },
    { name: "니우에", continent: "oceania", flag: "🇳🇺", capital: "알로피", population: "1,600명", area: "260 km²" },
    { name: "토켈라우", continent: "oceania", flag: "🇹🇰", capital: "파카오포", population: "1,400명", area: "12 km²" },
    { name: "피트케언 제도", continent: "oceania", flag: "🇵🇳", capital: "애덤스타운", population: "50명", area: "47 km²" },
    { name: "노퍽 섬", continent: "oceania", flag: "🇳🇫", capital: "킹스턴", population: "1,700명", area: "36 km²" },
    { name: "크리스마스 섬", continent: "oceania", flag: "🇨🇽", capital: "플라잉피시코브", population: "1,800명", area: "135 km²" },
    { name: "코코스 제도", continent: "oceania", flag: "🇨🇨", capital: "웨스트아일랜드", population: "600명", area: "14 km²" },
    { name: "왈리스 푸투나", continent: "oceania", flag: "🇼🇫", capital: "마타우투", population: "11,000명", area: "142 km²" },
    { name: "아메리칸 사모아", continent: "oceania", flag: "🇦🇸", capital: "파고파고", population: "55,000명", area: "199 km²" },
    { name: "괌", continent: "oceania", flag: "🇬🇺", capital: "하갓냐", population: "17만명", area: "549 km²" },
    { name: "북마리아나 제도", continent: "oceania", flag: "🇲🇵", capital: "사이판", population: "57,000명", area: "464 km²" }
]; 